#!/usr/bin/env bash
# display Ipv4 IPs on the machine
#!/bin/bash

if command -v ifconfig &> /dev/null; then
    ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
elif command -v ip &> /dev/null; then
    ip -4 addr show | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
fi
